In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('german_credit.csv', sep=r'\s+', header=None, engine='python', on_bad_lines='skip')

In [3]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,1,6,4,12,5,5,3,4,1,67,...,0,0,1,0,0,1,0,0,1,1
1,2,48,2,60,1,3,2,2,1,22,...,0,0,1,0,0,1,0,0,1,2
2,4,12,4,21,1,4,3,3,1,49,...,0,0,1,0,0,1,0,1,0,1
3,1,42,2,79,1,4,3,4,2,45,...,0,0,0,0,0,0,0,0,1,1
4,1,24,3,49,1,3,3,4,4,53,...,1,0,1,0,0,0,0,0,1,2

In [4]:
df.shape
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 25 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       1000 non-null   int64
 1   1       1000 non-null   int64
 2   2       1000 non-null   int64
 3   3       1000 non-null   int64
 4   4       1000 non-null   int64
 5   5       1000 non-null   int64
 6   6       1000 non-null   int64
 7   7       1000 non-null   int64
 8   8       1000 non-null   int64
 9   9       1000 non-null   int64
 10  10      1000 non-null   int64
 11  11      1000 non-null   int64
 12  12      1000 non-null   int64
 13  13      1000 non-null   int64
 14  14      1000 non-null   int64
 15  15      1000 non-null   int64
 16  16      1000 non-null   int64
 17  17      1000 non-null   int64
 18  18      1000 non-null   int64
 19  19      1000 non-null   int64
 20  20      1000 non-null   int64
 21  21      1000 non-null   int64
 22  22      1000 non-null   int64
 23  23      1000 non-null   int64
 24  24      1000 non-null   int64
dtypes: int64(25)
memory usage: 195.4 KB

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,1,6,4,12,5,5,3,4,1,67,...,0,0,1,0,0,1,0,0,1,1
1,2,48,2,60,1,3,2,2,1,22,...,0,0,1,0,0,1,0,0,1,2
2,4,12,4,21,1,4,3,3,1,49,...,0,0,1,0,0,1,0,1,0,1
3,1,42,2,79,1,4,3,4,2,45,...,0,0,0,0,0,0,0,0,1,1
4,1,24,3,49,1,3,3,4,4,53,...,1,0,1,0,0,0,0,0,1,2

In [5]:
df.shape

(1000, 25)

In [6]:
df.columns

Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24],
      dtype='int64')

In [7]:
df.iloc[:, -5:].head()

   20  21  22  23  24
0   1   0   0   1   1
1   1   0   0   1   2
2   1   0   1   0   1
3   0   0   0   1   1
4   0   0   0   1   2

In [8]:
df = df.drop(df.columns[21:], axis=1)

In [9]:
df.shape

(1000, 21)

In [10]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       1000 non-null   int64
 1   1       1000 non-null   int64
 2   2       1000 non-null   int64
 3   3       1000 non-null   int64
 4   4       1000 non-null   int64
 5   5       1000 non-null   int64
 6   6       1000 non-null   int64
 7   7       1000 non-null   int64
 8   8       1000 non-null   int64
 9   9       1000 non-null   int64
 10  10      1000 non-null   int64
 11  11      1000 non-null   int64
 12  12      1000 non-null   int64
 13  13      1000 non-null   int64
 14  14      1000 non-null   int64
 15  15      1000 non-null   int64
 16  16      1000 non-null   int64
 17  17      1000 non-null   int64
 18  18      1000 non-null   int64
 19  19      1000 non-null   int64
 20  20      1000 non-null   int64
dtypes: int64(21)
memory usage: 164.2 KB

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
dtype: int64

In [11]:
df.columns = [
    "duration", "credit_amount", "installment_rate", "residence_since",
    "age", "existing_credits", "num_dependents",
    "checking_account", "credit_history", "purpose", "savings",
    "employment", "personal_status", "other_debtors",
    "property", "other_installment_plans", "housing",
    "job", "telephone", "foreign_worker", "credit_risk"
]

In [12]:
X = df.drop('credit_risk', axis=1)
Y = df['credit_risk']

In [18]:
from sklearn.model_selection import train_test_split

Xtrain,Xtest,Ytrain,Ytest = train_test_split(X, Y, test_size=0.2, random_state=42, stratify=Y)

In [19]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
Xtrain_scaled = scaler.fit_transform(Xtrain)
Xtest_scaled  = scaler.transform(Xtest)

In [22]:
from sklearn.linear_model import LogisticRegression

logistic_tuned = LogisticRegression(C=0.5, max_iter=1000, solver='liblinear')
logistic_tuned.fit(Xtrain_scaled,Ytrain)

LogisticRegression(C=0.5, max_iter=1000, solver='liblinear')

In [24]:
y_pred = logistic_tuned.predict(Xtest_scaled)

In [25]:
from sklearn.metrics import classification_report
print(classification_report(Ytest,y_pred))

              precision    recall  f1-score   support

           0       0.89      0.96      0.92        57
           1       0.99      0.95      0.97       143

    accuracy                           0.95       200
   macro avg       0.94      0.96      0.95       200
weighted avg       0.96      0.95      0.96       200

In [26]:
#0 → Not creditworthy (bad customer)

#1 → Creditworthy (good customer)

In [27]:
from sklearn.metrics import accuracy_score

# predict on test data
y_pred = logistic_tuned.predict(Xtest_scaled)

# accuracy
accuracy = accuracy_score(Ytest, y_pred)
print("Model Accuracy:", accuracy)

Model Accuracy: 0.955

In [16]:
creditworthy_user = Xtrain[Ytrain == 1].iloc[0].values.reshape(1, -1)
creditworthy_user_scaled = scaler.transform(creditworthy_user)

pred = logistic_tuned.predict(creditworthy_user_scaled)
prob = logistic_tuned.predict_proba(creditworthy_user_scaled)[0][1]

print("Prediction:", pred)
print("Probability:", prob)

Prediction: [1]
Probability: 0.9840394637705504

/opt/anaconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [17]:
if pred[0] == 1:
    print("✅ User is CREDITWORTHY")
else:
    print("❌ User is NOT CREDITWORTHY")

✅ User is CREDITWORTHY

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV

logistic = LogisticRegression(max_iter=1000)

grid = GridSearchCV(
    estimator=logistic,
    param_grid=param_grid,
    cv=5,
    scoring='roc_auc',   # BETTER than accuracy
    n_jobs=-1
)

grid.fit(Xtrain_scaled, Ytrain)

print("Best Parameters:", grid.best_params_)
print("Best Score:", grid.best_score_)

Best Parameters: {'C': 0.1, 'penalty': 'l1', 'solver': 'liblinear'}
Best Score: 0.9890732265446225

In [35]:
from sklearn.metrics import accuracy_score, classification_report, roc_auc_score

y_test_pred = logistic_tuned.predict(Xtest_scaled)
y_test_prob = logistic_tuned.predict_proba(Xtest_scaled)[:, 1]

print("Test Accuracy:", accuracy_score(Ytest, y_test_pred))
print(classification_report(Ytest, y_test_pred))
print("Test ROC-AUC:", roc_auc_score(Ytest, y_test_prob))

Test Accuracy: 0.96
              precision    recall  f1-score   support

           0       0.90      0.96      0.93        57
           1       0.99      0.96      0.97       143

    accuracy                           0.96       200
   macro avg       0.94      0.96      0.95       200
weighted avg       0.96      0.96      0.96       200

Test ROC-AUC: 0.9943565206723102

In [ ]:
# Now checking this model for a new data whether the user is creditworthy or not

In [41]:
# Take one REAL creditworthy user from dataset
user = Xtrain[Ytrain == 1].iloc[0].values.reshape(1, -1)

user_scaled = scaler.transform(user)
pred = logistic_tuned.predict(user_scaled)[0]
prob = logistic_tuned.predict_proba(user_scaled)[0][1]

if pred == 1:
    print("User is CREDITWORTHY")
else:
    print("User is NOT CREDITWORTHY")

print(f"Confidence: {prob:.2f}")

User is CREDITWORTHY
Confidence: 0.94

/opt/anaconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(